#page title
page_title                                : StatShot                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6745430902                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : StatShot - Share your activity                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Turn your Strava stats into stunning visuals

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : senne.scheepers@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : statshot.app
tiktok_username                           : statshot.app
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Strava Integration
    description                           : Seamlessly connect with Strava and turn your activities into shareable content.
    fontawesome_icon_name                 : "brands fa-strava"

  - title                                 : Image & Video Overlays
    description                           : Add Strava stats to both photos and videos, with styles that stand out.
    fontawesome_icon_name                 : photo-film
    
  - title                                 : Easy Export
    description                           : Share your StatShot straight to Instagram, TikTok, ... Or save it to your Camera Roll in seconds.
    fontawesome_icon_name                 : arrow-up-from-bracket

  - title                                 : Built-In Crop & Fit
    description                           : Optimized for TikTok, Instagram, and Stories. No resizing headaches.
    fontawesome_icon_name                 : crop-simple

  - title                                 : No Account Needed
    description                           : No logins, no signups. Just open and create.
    fontawesome_icon_name                 : user-slash



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header.jpg                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : iphone                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#5FBF94"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#5FBF94"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
